export {
  DashboardOutlined,
  BookOutlined,
  FileTextOutlined,
  UserOutlined,
  TeamOutlined,
  SettingOutlined,
  LogoutOutlined,
  LeftOutlined,
  RightOutlined,
  ArrowLeftOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  LoadingOutlined,
} from '@ant-design/icons';
